on:
    pull_request:
        branches:
            - master
            - develop
    workflow_dispatch:

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/cache@v3
              with:
                  path: |
                      node_modules
                      .yarn/cache
                  key: node_modules-${{ hashFiles('**/yarn.lock') }}
            - run: yarn
            - run: yarn lint:ci
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/cache@v3
              with:
                  path: |
                      node_modules
                      .yarn/cache
                  key: node_modules-${{ hashFiles('**/yarn.lock') }}
            - run: yarn
            - run: yarn build
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: cp ./.env.example  ./.env
            - run: yarn
            - run: yarn database:setup
            - run: yarn test
